    jenkins_user: jenkins
    jenkins_pass: jenkins85g
    download_folder: /opt
    jenkins_download_url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    jenkins_key_url: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    jenkins_repo_path: /etc/yum.repos.d/jenkins.repo
    maven_download_url: https://www-us.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
    maven_name: "{{download_folder}}/apache-maven-3.6.0"