---
- name: Install Java
  package:
    name:
      - java-1.8.0-openjdk
    state: latest  

- name: Download Apache Maven 
  unarchive:
    src: "{{ maven_download_url }}"
    dest: "{{ download_folder }}"
    remote_src: yes

- name: Fix ownership
  file: state=directory path={{maven_name}} owner=root group=root recurse=yes

- name: Make Maven available for system
  command: 'alternatives --install "/usr/bin/maven" "maven" "{{maven_name}}/bin/maven" 2000'